name: "🌐 Other Report"
description: Report an issue or possible bug.
title: "🌐 [OTHER] - <title>"
body:
  - type: textarea
    id: issue
    attributes:
      label: "📋 Explain your issue"
      description: Feel free to explain your issue
      placeholder: "..."
    validations:
        required: true