name: "🌐 Other Report"
description: Report an issue or possible bug.
title: "🌐 [OTHER] - <title>"
body:
  - type: textarea
    id: issue
    attributes:
      label: "📋 Explain your issue"
      description: Try to give us a precise description of the issue, so we can try to solve it as soon as possible
      placeholder: "..."
    validations:
        required: true